config/routes.rb
Homebanking::Application.routes.draw do
  devise_for :correntista

  devise_for :funcionarios

  resources :transacaos

  resources :funcionarios

  resources :correntista

  resources :conta
  resources :contacriar

    match '/' => 'conta#index'
    match '/saque' => 'conta#saque'
    match '/deposito' => 'conta#deposito'
  match '/transferencia' => 'conta#transferencia'
  match '/usu/deposito' => 'contacriar#deposito'
    match '/usu/transferencia' => 'contacriar#transferencia'
    match '/usu/extrato' => 'contacriar#extrato'
    match '/extrato' => 'conta#extrato'
    match '/usu/saldo' => 'contacriar#saldo'
    match '/saldo' => 'conta#saldo'

end

app/models/transacao.rb
class Transacao < ActiveRecord::Base
  set_primary_key :codigo
  attr_accessible :codigo, :data, :nro_conta, :nro_conta_transf, :tipo, :valor
end

app/controllers/transacaos_controller.rb
class TransacaosController < ApplicationController
  before_filter :authenticate_correntistum!, :except => [:destroy,:update]
  before_filter :authenticate_funcionario!, :except => [:show, :index]
  # GET /transacaos
  # GET /transacaos.json
  def index
    #@transacaos = Transacao.all
    @numero_conta = Contum.find_by_primeiro_corr(current_correntistum.cpf)
    @transacaos = Transacao.where(:nro_conta=>@numero_conta.numero)
    #@transacaos = Transacao.where(:nro_conta=>current_correntistum.contum.numero)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transacaos }
    end
  end

  # GET /transacaos/1
  # GET /transacaos/1.json
  def show
    @transacao = Transacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transacao }
    end
  end

  # GET /transacaos/new
  # GET /transacaos/new.json
  def new
    @transacao = Transacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transacao }
    end
  end

  # GET /transacaos/1/edit
  def edit
    @transacao = Transacao.find(params[:id])
  end

  # POST /transacaos
  # POST /transacaos.json
  def create
    @transacao = Transacao.new(params[:transacao])

    respond_to do |format|
      if @transacao.save
        format.html { redirect_to @transacao, notice: 'Transacao was successfully created.' }
        format.json { render json: @transacao, status: :created, location: @transacao }
      else
        format.html { render action: "new" }
        format.json { render json: @transacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transacaos/1
  # PUT /transacaos/1.json
  def update
    @transacao = Transacao.find(params[:id])

    respond_to do |format|
      if @transacao.update_attributes(params[:transacao])
        format.html { redirect_to @transacao, notice: 'Transacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transacaos/1
  # DELETE /transacaos/1.json
  def destroy
    @transacao = Transacao.find(params[:id])
    @transacao.destroy

    respond_to do |format|
      format.html { redirect_to transacaos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transacaos_helper.rb
module TransacaosHelper
end

app/views/transacaos/_form.html.erb
<%= form_for(@transacao) do |f| %>
  <% if @transacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transacao.errors.count, "error") %> prohibited this transacao from being saved:</h2>

      <ul>
      <% @transacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.number_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :nro_conta %><br />
    <%= f.number_field :nro_conta %>
  </div>
  <div class="field">
    <%= f.label :nro_conta_transf %><br />
    <%= f.number_field :nro_conta_transf %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transacaos/edit.html.erb
<h1 class="text-center">Editar Transação</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @transacao, class:"btn btn-primary" %> |
<%= link_to 'Voltar', transacaos_path, class:"btn btn-inverse" %>

app/views/transacaos/index.html.erb
<h1 class="text-center">Todas as Transações</h1>

<br />

<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Codigo</th>
    <th>Tipo</th>
    <th>Conta Origem</th>
    <th>Conta Destino</th>
    <th>Valor</th>
    <th>Data</th>
  </tr>
  </thead>

  <tbody>
<% @transacaos.each do |transacao| %>
  <tr>
    <td><%= transacao.codigo %></td>
    <td><%= transacao.tipo %></td>
    <td><%= transacao.nro_conta %></td>
    <td><%= transacao.nro_conta_transf %></td>
    <td><%= transacao.valor %></td>
    <td><%= transacao.data.strftime("%d/%m/%y") %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/transacaos/new.html.erb
<h1 class="text-center">Nova Transação</h1>

<%= render 'form' %>

<%= link_to 'Voltar', transacaos_path, class:"btn btn-inverse" %>

app/views/transacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @transacao.codigo %>
</p>

<p>
  <b>Tipo:</b>
  <%= @transacao.tipo %>
</p>

<p>
  <b>Nro conta:</b>
  <%= @transacao.nro_conta %>
</p>

<p>
  <b>Nro conta transf:</b>
  <%= @transacao.nro_conta_transf %>
</p>

<p>
  <b>Valor:</b>
  <%= @transacao.valor %>
</p>

<p>
  <b>Data:</b>
  <%= @transacao.data %>
</p>


<%= link_to 'Editar', edit_transacao_path(@transacao), class:"btn btn-warning" %> |
<%= link_to 'Voltar', transacaos_path, class:"btn btn-inverse" %>