config/routes.rb
Homebanking::Application.routes.draw do
  devise_for :correntista

  devise_for :funcionarios

  resources :transacaos

  resources :funcionarios

  resources :correntista

  resources :conta
  resources :contacriar

    match '/' => 'conta#index'
    match '/saque' => 'conta#saque'
    match '/deposito' => 'conta#deposito'
  match '/transferencia' => 'conta#transferencia'
  match '/usu/deposito' => 'contacriar#deposito'
    match '/usu/transferencia' => 'contacriar#transferencia'
    match '/usu/extrato' => 'contacriar#extrato'
    match '/extrato' => 'conta#extrato'
    match '/usu/saldo' => 'contacriar#saldo'
    match '/saldo' => 'conta#saldo'

end

app/controllers/contacriar_controller.rb
class ContacriarController < ApplicationController
      before_filter :authenticate_correntistum!


      def index

        @conta = Contum.where("primeiro_corr = '#{current_correntistum.cpf}' or  segundo_corr= '#{current_correntistum.cpf}' or terceiro_corr  = '#{current_correntistum.cpf}'")

        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @conta }
        end


      end


  # GET /conta/1
  # GET /conta/1.json
  def show
    @contum = Contum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contum }
    end
  end

  # GET /conta/new
  # GET /conta/new.json
  def new
    @contum = Contum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contum }
    end
  end

  # GET /conta/1/edit
  def edit
    @contum = Contum.find(params[:id])
  end

  # POST /conta
  # POST /conta.json
  def create
    @contum = Contum.new(params[:contum])

    respond_to do |format|
      if @contum.save
        format.html { redirect_to @contum, notice: 'Contum was successfully created.' }
        format.json { render json: @contum, status: :created, location: @contum }
      else
        format.html { render action: "new" }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conta/1
  # PUT /conta/1.json
  def update
    @contum = Contum.find(params[:id])

    respond_to do |format|
      if @contum.update_attributes(params[:contum])
        format.html { redirect_to @contum, notice: 'Contum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conta/1
  # DELETE /conta/1.json
  def destroy
    @contum = Contum.find(params[:id])
    @contum.destroy

    respond_to do |format|
      format.html { redirect_to conta_url }
      format.json { head :no_content }
    end
  end

  def saque
    @conta=Contum.find(params[:conta])
    if @conta.saldo.to_f-params[:saque].to_f>=0
      @conta.update_attribute(:saldo,@conta.saldo.to_f-params[:saque].to_f)
      Transacao.create(:codigo=>DateTime.now.to_i, :data=>Date.today, :nro_conta=>params[:conta], :tipo=>'saque', :valor=>params[:saque])
      respond_to do |format|
        format.html { redirect_to contacriar_url,alert: "Saque Efetuado com sucesso Saldo diponivel#{@conta.saldo}" }
        format.json { head :no_content }
      end
    elsif (@conta.saldo.to_f+@conta.limite.to_f)-params[:saque].to_f>=0
      aux=@conta.saldo.to_f-params[:saque].to_f
      if aux<0
        @conta.limite=@conta.limite.to_f+aux
        @conta.saldo=0
      end
      @conta.update_attributes(:saldo=>@conta.saldo,:limite=>@conta.limite)
      Transacao.create(:codigo=>DateTime.now.to_i, :data=>Date.today, :nro_conta=>params[:conta], :tipo=>'saque', :valor=>params[:saque])
      respond_to do |format|
        format.html { redirect_to contacriar_url,alert: "Saque Efetuado com sucesso Saldo diponivel#{@conta.saldo}" }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to contacriar_url,alert: "Saldo insdiponivel" }
        format.json { head :no_content }
      end
    end
  end

  def deposito
    @conta=Contum.find(params[:conta])
    @conta.update_attributes(:saldo=>params[:saque].to_f+@conta.saldo.to_f)
    Transacao.create(:codigo=>DateTime.now.to_i, :data=>Date.today,:nro_conta=>params[:conta], :tipo=>'deposito', :valor=>params[:saque])
    respond_to do |format|
      format.html { redirect_to contacriar_url,notice: "Deposito efetuado com sucesso novo" }
      format.json { head :no_content }
    end
  end

  def transferencia
    @conta=Contum.find(params[:origem])
    @conta2=Contum.find(params[:destino])
    if (@conta.saldo.to_f+@conta.limite.to_f)-params[:valor].to_f>=0
      aux=@conta.saldo.to_f-params[:valor].to_f
      if aux <=0
        @conta.limite=@conta.limite-aux
        @conta.saldo=0
      else
        @conta.saldo=aux
      end
        @conta.update_attributes(:saldo=>@conta.saldo,:limite=>@conta.limite)
        @conta2.update_attribute(:saldo,(@conta2.saldo+params[:valor].to_f))
        Transacao.create(:codigo=>DateTime.now.to_i, :data=>Date.today,:nro_conta=>params[:origem], :nro_conta_transf=>params[:destino],:tipo=>'transf', :valor=>params[:saque])

      @conta
        respond_to do |format|
          format.html { redirect_to "/contacriar",notice: "Tranferencia efetuada com sucesso!" }
          format.json { head :no_content }
        end
      end

  end

  def extrato
           @extrato=Transacao.where("nro_conta = ?  and data > ?",params[:conta],params[:data].to_date-30)
  end

  def saldo
        @conta=Contum.find_by_numero(params[:conta])
  end

end

app/views/contacriar/_form.html.erb
<%= form_for(@contum) do |f| %>
  <% if @contum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contum.errors.count, "error") %> prohibited this contum from being saved:</h2>

      <ul>
      <% @contum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %>
    <%= f.number_field :numero %>
  </div>
    <br />
  <div class="field">
    <%= f.label :primeiro_corr %>
    <%= f.text_field :primeiro_corr %>
  </div>
    <br />
  <div class="field">
    <%= f.label :segundo_corr %>
    <%= f.text_field :segundo_corr %>
  </div>
    <br />
  <div class="field">
    <%= f.label :terceiro_corr %>
    <%= f.text_field :terceiro_corr %>
  </div>
    <br />
    <div class="field">
      <%= f.label :saldo %>
      <%= f.text_field :saldo %>
    </div>
    <br />
  <div class="field">
    <%= f.label :limite %>
    <%= f.text_field :limite %>
  </div>
    <br />
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/contacriar/edit.html.erb
<h1 class="text-center">Editar Conta</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @contum, class:"btn btn-primary" %> |
<%= link_to 'Voltar', conta_path, class:"btn btn-inverse" %>

app/views/contacriar/extrato.html.erb
<h2 class="text-center">Extrato</h2>

<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Codigo</th>
    <th>Tipo</th>
    <th>Conta Origem</th>
    <th>Conta Destino</th>
    <th>Valor</th>
    <th>Data</th>
  </tr>
  </thead>

  <tbody>
  <% @extrato.each do |transacao| %>
      <tr>
        <td><%= transacao.codigo %></td>
        <td><%= transacao.tipo %></td>
        <td><%= transacao.nro_conta %></td>
        <td><%= transacao.nro_conta_transf %></td>
        <td><%= transacao.valor %></td>
        <td><%= transacao.data.strftime("%d/%m/%y") %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Voltar', :back, class:"btn btn-inverse" %>

app/views/contacriar/index.html.erb
<h1 class="text-center">Todas as Contas</h1>


<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Numero</th>
    <th>Primeiro corr</th>
    <th>Segundo corr</th>
    <th>Terceiro corr</th>
    <th>Saldo</th>
    <th>Limite</th>
  </tr>
  </thead>

  <tbody>
  <% @conta.each do |contum| %>
      <tr>
        <td><%= contum.numero %></td>
        <td><%= contum.primeiro_corr %></td>
        <td><%= contum.segundo_corr %></td>
        <td><%= contum.terceiro_corr %></td>
        <td><%= contum.saldo %></td>
        <td><%= contum.limite %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br />

<a class="btn collapse-data-btn" data-toggle="collapse" href="#transferencia">Tranferência</a>
<a class="btn collapse-data-btn" data-toggle="collapse" href="#saldo">Saldo</a>
<a class="btn collapse-data-btn" data-toggle="collapse" href="#extrato">Extrato</a>
<br><br>


<div id="transferencia" class="collapse">
  <form action="/usu/transferencia">
    Transferência<br>
    Nº Conta Origem: <input name="origem" type="number"> <br>
    Nº Conta Destino: <input name="destino" type="number"><br>
    Valor a Transferir: <input name="valor" type="number">
    <input value="Transferir" type="submit" class="btn btn-success" >
  </form>
</div>
<div id="saldo" class="collapse">
  <form action="/usu/saldo">
    Saldo<br>
    Nº Conta:  <input name="conta" type="number"> <br>
    <input value="saldo" type="submit" class="btn btn-success" >
  </form>
</div>
<div id="extrato" class="collapse">
  <form action="/usu/extrato">
    Extrato<br>
    Nº Conta: <input name="conta" type="number"> <br>
   Data: <input name="data" type="text" placeholder="aaaa-mm-dd">
    <input value="enviar" type="submit" class="btn btn-success" >
  </form>
</div>

app/views/contacriar/new.html.erb
<h1 class="text-center">Nova Conta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', conta_path, class:"btn btn-inverse" %>

app/views/contacriar/saldo.html.erb
<p class="well">
Saldo na conta <%= @conta.numero%>  é de R$ <%= @conta.saldo %>
</p>

<%= link_to 'Voltar', :back, class:"btn btn-inverse" %>

app/views/contacriar/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numero:</b>
  <%= @contum.numero %>
</p>

<p>
  <b>Primeiro Correntista:</b>
  <%= @contum.primeiro_corr %>
</p>

<p>
  <b>Segundo Correntista:</b>
  <%= @contum.segundo_corr %>
</p>

<p>
  <b>Terceiro Correntista:</b>
  <%= @contum.terceiro_corr %>
</p>

<p>
  <b>Limite:</b>
  <%= @contum.limite %>
</p>


<%= link_to 'Editar', edit_contum_path(@contum), class:"btn btn-warning" %> |
<%= link_to 'Voltar', contacriar_path, class:"btn btn-inverse" %>