config/routes.rb
Homebanking::Application.routes.draw do
  devise_for :correntista

  devise_for :funcionarios

  resources :transacaos

  resources :funcionarios

  resources :correntista

  resources :conta
  resources :contacriar

    match '/' => 'conta#index'
    match '/saque' => 'conta#saque'
    match '/deposito' => 'conta#deposito'
  match '/transferencia' => 'conta#transferencia'
  match '/usu/deposito' => 'contacriar#deposito'
    match '/usu/transferencia' => 'contacriar#transferencia'
    match '/usu/extrato' => 'contacriar#extrato'
    match '/extrato' => 'conta#extrato'
    match '/usu/saldo' => 'contacriar#saldo'
    match '/saldo' => 'conta#saldo'

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  set_primary_key :codigo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :codigo, :email, :endereco, :funcao, :nome, :senha
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_filter :authenticate_funcionario!

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funcionarios }
    end
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
    @funcionario = Funcionario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/new
  # GET /funcionarios/new.json
  def new
    @funcionario = Funcionario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/1/edit
  def edit
    @funcionario = Funcionario.find(params[:id])
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(params[:funcionario])

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render json: @funcionario, status: :created, location: @funcionario }
      else
        format.html { render action: "new" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /funcionarios/1
  # PUT /funcionarios/1.json
  def update
    @funcionario = Funcionario.find(params[:id])

    respond_to do |format|
      if @funcionario.update_attributes(params[:funcionario])
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario = Funcionario.find(params[:id])
    @funcionario.destroy

    respond_to do |format|
      format.html { redirect_to funcionarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password, "senha" %><br />
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :funcao %><br />
    <%= f.select :funcao, (['Gerente','Caixa','Atendente']) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1 class="text-center">Editar Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @funcionario, class:"btn btn-primary" %> |
<%= link_to 'Voltar', funcionarios_path, class:"btn btn-inverse" %>

app/views/funcionarios/index.html.erb
<h1 class="text-center">Todos os Funcionarios</h1>

<p>
  <%= link_to 'Novo Funcionario', new_funcionario_path, class:"btn" %>
</p>

<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Codigo</th>
    <th>Nome</th>
    <th>Email</th>
    <th>Funcao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
<% @funcionarios.each do |funcionario| %>
  <tr>
    <td><%= funcionario.codigo %></td>
    <td><%= funcionario.nome %></td>
    <td><%= funcionario.email %></td>
    <td><%= funcionario.funcao %></td>
    <td><%= link_to 'Visualizar', funcionario, class:"btn btn-primary" %></td>
    <td><%= link_to 'Editar', edit_funcionario_path(funcionario), class:"btn btn-warning" %></td>
    <td><%= link_to 'Apagar', funcionario, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/funcionarios/new.html.erb
<h1 class="text-center">Novo Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Voltar', funcionarios_path, class:"btn btn-inverse" %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @funcionario.codigo %>
</p>

<p>
  <b>Nome:</b>
  <%= @funcionario.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @funcionario.email %>
</p>

<p>
  <b>Funcao:</b>
  <%= @funcionario.funcao %>
</p>


<%= link_to 'Editar', edit_funcionario_path(@funcionario), class:"btn btn-warning" %> |
<%= link_to 'Voltar', funcionarios_path, class:"btn btn-inverse" %>