config/routes.rb
Homebanking::Application.routes.draw do
  devise_for :correntista

  devise_for :funcionarios

  resources :transacaos

  resources :funcionarios

  resources :correntista

  resources :conta
  resources :contacriar

    match '/' => 'conta#index'
    match '/saque' => 'conta#saque'
    match '/deposito' => 'conta#deposito'
  match '/transferencia' => 'conta#transferencia'
  match '/usu/deposito' => 'contacriar#deposito'
    match '/usu/transferencia' => 'contacriar#transferencia'
    match '/usu/extrato' => 'contacriar#extrato'
    match '/extrato' => 'conta#extrato'
    match '/usu/saldo' => 'contacriar#saldo'
    match '/saldo' => 'conta#saldo'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homebanking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
      <% end %>

    <% if funcionario_signed_in? %>
      <p class="navbar-inner text-right">
        Olá <%= current_funcionario.funcao%> <strong> <%= current_funcionario.nome%></strong>!
        <%= link_to 'Editar Perfil', edit_funcionario_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Sair", destroy_funcionario_session_path, method: :delete, :class => 'navbar-link btn btn-danger'  %>
    <% elsif correntistum_signed_in? %>
      <p class="navbar-inner text-right">
        Olá <strong> <%= current_correntistum.nome%></strong>!
        <%= link_to "Sair", destroy_correntistum_session_path, method: :delete, :class => 'navbar-link btn btn-danger'  %>
    <% end %>


  <%= yield %>
</div>
</body>
</html>